### ISSUE TITLE
Upgrade to use OpenSearch java client

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-common#15]

**Comment by jordanpadams** [comment]
need to investigate if this was completed by another ticket

**Comment by tloubrieu-jpl** [comment]
We don't need to upgrade this library for this build.

**Comment by jordanpadams** [comment]
descoping from B12.1 since it is not required.

@tloubrieu-jpl @jimmie @ramesh-maddegoda will this ever be required? Or was the registry-api the only thing that needed to be updated?

**Comment by jordanpadams** [comment]
This has been merged to main
