### ISSUE TITLE
NJsonDocUtils.writeField() converts single-element-valued collection to String

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-common#29]
## 🐛 Describe the bug
When encountering a collection-valued field with size 1, [writeField() explicitly writes a String instead of an Array with a single String element](https://github.com/NASA-PDS/registry-common/blob/main/src/main/java/gov/nasa/pds/registry/common/util/json/NJsonDocUtils.java#L116)

This is resulting in undesirable behaviour in [some cases](https://github.com/NASA-PDS/registry-mgr/issues/57).

This must be fixed, but given that someone wrote it intentionally I'm loathe to unilaterally change it in case there are some cases where it's desirable - from what I've seen this will result in numerous fields being "corrected", not just `ref_lid_collection`.

## 📜 To Reproduce
1. Harvest any bundle containing a single collection (e.g. https://pdssbn.astro.umd.edu/holdings/pds4-epoxi_mri-v1.0/)
, into a registry instance
2. Query OpenSearch for that bundle (e.g. with `curl -k -u admin:admin https://localhost:9200/registry/_doc/urn:nasa:pds:epoxi_mri::1.0?_source=ref_lidvid_collection,ref_lid_collection | json_pp`)
3. Observe the value of `ref_lid_collection`

## 🕵️ Expected behavior
Unclear.  Collection-like fields should be written as Arrays, but if there are cases where conversion is desired/required, these must be accounted for and not affected by the fix.

## 📚 Version of Software Used
registry-common==1.4.0

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl gonna need either permission to fix this in all cases, or some context for when it's desirable to convert a single-element string array to a string, to prevent this from potentially breaking a whole bunch of stuff (i.e. if end-users are reading such fields programmatically)

**Comment by alexdunnjpl** [comment]
[Conversion originally implemented in this commit](https://github.com/NASA-PDS/harvest/commit/baa79aab56b2c69fd0c8f560c1d198389bcc44ac)

The commit message is unrelated/opaque.

**Comment by alexdunnjpl** [comment]
Oh, looks like it's a reimplementation of existing functionality that was unintentionally deleted in the previous commit.

[Original source is here](https://github.com/NASA-PDS/harvest/blame/d42e52f5bf54eefbb9343b6f09cea837e9416ef5/src/main/java/gov/nasa/pds/harvest/util/out/NDJsonDocUtils.java#L57) and/or [here](https://github.com/NASA-PDS/harvest/pull/27/commits/815d92f3525d9a5fe6960d1e62c06893dd9f8ad4#diff-9840662975c280382f9288b0f1c231e41cf62ae0b570a05736b5d7a3c1ba16eaR27)

**Comment by jordanpadams** [comment]
@alexdunnjpl unless @tloubrieu-jpl has an objection, let's march forward with a PR fix, and we can evaluate if that is something we do not want to do

**Comment by tloubrieu-jpl** [comment]
I cannot be 100% sure, but it is slowly emerging from my memories that without this we would have all the properties values show as arrays even if there is a single value. See screenshot:
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/60993872/204580341-28931d46-7387-44a8-a68d-850173f37534.png">

Instead of scalar values we would have arrays with length 1. I remember I asked that change to Eugene when I started the development of the API service.

But I agree this code does not look good and I would prefer if we have an option not to have arrays values in the first place for single values. That might be related to the XML parser which is used ? @alexdunnjpl could you have a look at that ?

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl will dig in to make sure I'm not misremembering something, but it sounds like the core issue is that there's a generic "properties" flow which processes fields with either collection-like or string-like values (depending on the field), but currently has no way of differentiating between the two cases.

My gut feeling is that we should know prima facie what the collection-like properties are, and should therefore be able to detect "collection-like strings" and "everything else" and process them accordingly?  I'm not certain that's a valid assumption though, and I'd probably want help enumerating the collection-likes unless they're trivially-obvious to track down.

**Comment by alexdunnjpl** [comment]
Taking a closer look, `NJsonDocUtils.writeField()` is signature-polymorphic, so the behaviour is due to the fact that `writeField()` is passed a `Collection<String>` in the first place.  This supports the idea that the root/fix is in the xml parsing.

**Comment by alexdunnjpl** [comment]
[The imprecisely-typed metadata construction occurs in `harvest`, here](https://github.com/NASA-PDS/harvest/blob/main/src/main/java/gov/nasa/pds/harvest/crawler/FilesProcessor.java#L195-L240).

At a glance, it looks pretty fraught to retroactively introduce any concept of typing here.  It seems like the idea that metadata field values will be extracted into collections is pretty baked in.  If that's the case, it may be least-worst to fall back to Eugene's original approach (i.e. the JSON writer is responsible for "typing" the fields) and extract the "convert to a single value" conditional to a function that encapsulates the business logic for making the differentiation - instead of `if size == 1`, something like `if size == 1 and fieldName not in collectionTypedFieldNames`

@tloubrieu-jpl @jordanpadams thoughts?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @jshughes could we use the PDS information model (schema, schematron) to tell which element should be treated as an array, which one should not ?

**Comment by alexdunnjpl** [comment]
Per stand-up meeting, solution is to remove scalar conversion - all fields will be written as arrays

**Comment by tloubrieu-jpl** [comment]
Since the API is showing these values as arrays anyway (see https://pds.nasa.gov/api/search/1.0/products) we will remove the condition in registry-common to always save collections as arrays in OpenSearch.
