### ISSUE TITLE
Augment authentication behaviour to support Cognito credential set

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-common#36]
## 💡 Description
Currently, auth.cfg contains a user/pass set which is passed to OpenSearch as a Basic header.  It is now necessary to support Cognito alongside Basic auth (Basic may be deprecated later).

This will required shoehorning additional functionality into `gov.nasa.pds.registry.common.es.client.EsRestClientBld` (probably).

[See Slack convo for more details](https://jpl.slack.com/archives/C0566EJBGJU/p1684792073753829)

May be smart to depend this issue on https://github.com/NASA-PDS/registry-common/issues/15 if still applicable (it appears so - `registry-commons` is still using an ElasticSearch client)

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl can consider realizing this ticket https://github.com/NASA-PDS/registry-common/issues/15 for the current task.

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl is working on that.

**Comment by jordanpadams** [comment]
@alexdunnjpl continuing to work on this.

**Comment by nutjob4life** [comment]
Back and forth w/@nutjob4life and on hold today due to provenance issues

**Comment by tloubrieu-jpl** [comment]
@nutjob4life is taking that on his shoulders

**Comment by tloubrieu-jpl** [comment]
@nutjob4life can you pause on that development ? We have just discussed during the breakout that the multitenant deployment might use a serverless version of the AWS managed opensearch which does not support Cognito as an authentication system.

If we go for that, we would implement the cognito authentication in API proxies in front of opensearch. That would change/simplify the authentication for harvest/registry-mgr. Maybe we would have one API end-point for each opensearch role... That to say, you should not spend more time on this ticket until we know better what we are going to do.

We are waiting for expert feedback on the opensearch solution chosen before we move on. We'll let you know.

**Comment by nutjob4life** [comment]
@tloubrieu-jpl I pressed the ⏸️ button on this ticket. However, this is my only ticket! I need something else to work on.

**Comment by tloubrieu-jpl** [comment]
Blocked until we decide on the AWS OpenSearch service we eventually use.

**Comment by tloubrieu-jpl** [comment]
Regarding the signed URL management there is some new doc: https://code.dblock.org/2022/07/11/making-sigv4-authenticated-requests-to-managed-opensearch.html

**Comment by al-niessner** [comment]
@nutjob4life @alexdunnjpl @jordanpadams @tloubrieu-jpl 

I need to make some pretty sweeping changes for cognito: see NASA-PDS/harvest#146 if you like gore. Point is, it looks like it y'all may have done some of it already. Maybe you had a different plan of attack. I want to make a bunch of the classes polymorphic so that we do not have CollectionWriterHTTPS and CollectionWriterCognito sprinkled heavily throughout the code. Do you all have a branch with changes on it that you could push/PR so that I can see where it is at and maybe where it was going before the great pause.

**Comment by alexdunnjpl** [comment]
@al-niessner I've added you to that slack convo, and mailed over snips from another DM between Sean and I which may have some useful gotchas/thoughts.

**Comment by tloubrieu-jpl** [comment]
To be tested with harvest and registry-common before we merge.

**Comment by tloubrieu-jpl** [comment]
@al-niessner is working with the lambda now and experimenting issues with it. @sjoshi-jpl is investigation this issues.

**Comment by tloubrieu-jpl** [comment]
There are issues when using the opensearch java sdk with the api gateway proxy. To be discussed at the breakout.

**Comment by tloubrieu-jpl** [comment]
@al-niessner is progressing on using and expending the OpenSearch AWS SDK to work with Cognito authentication.

**Comment by tloubrieu-jpl** [comment]
@al-niessner was able to get the credential from the lambda developed by @sjoshi-jpl .

now he's getting a 404 error when trying to reach to the OpenSearch server.

**Comment by tloubrieu-jpl** [comment]
The new SDK requires some more updates.

**Comment by jordanpadams** [comment]
Status: PR created to fix bug introduced with initial refactoring.
