### ISSUE TITLE
Update OpenSearch API call to use `search()` instead of `get()`

### ISSUE THREAD

**Issue by al-niessner** [NASA-PDS/registry-common#53]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When using lid/lidvids, the ':'s cause problems but work fine in search.

### 🕵️ Expected behavior

I expected finding documents via lidvids to work unconditionally.

### 📜 To Reproduce

1. Do an opensearch get() operation using AOSS Java SDK v2 and the ID as a lidvid to get a 404 return.
2. Do an opensearch search() operation using AOSS Java SDK v2 for lidvid and it will work.

### 🖥 Environment Info

- any with AOSS

### 🦄 Related requirements

NASA-PDS/registry-mgr#78

**Comment by al-niessner** [comment]
No longer needed. Delete of data is being rewritten and GetRequest works with opensearch-java-3.0.0-SNAPSHOT.

**Comment by jordanpadams** [comment]
Skipping I&T. Internal library update that can be tested by and harvest / registry manage smoke test
