### ISSUE TITLE
As a Nucleus system, I want to be able to invoke harvest and registry-mgr from within the AWS VPC

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-common#83]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

The Nucleus system is the actual user,

### 💪 Motivation

...so that I can interact with the registry from nucleus.

### 📖 Additional Details

We need a specific registry connection configuration, which would not use login/password or the credentials API.

To connect to OpenSearch serverless we will use the credentials of the IAM role associated to the host of the process (ECS, EC2).

The credentials need to be renewed when they expire.

We could use code like the one used by the registry-api, see https://github.com/NASA-PDS/registry-api/blob/main/service/src/main/java/gov/nasa/pds/api/registry/util/AWSCredentialsFetcher.java

Related documentation can be found on https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html

The current configuration connection does not work for Nucleus because harvest runs on our internal AWS networks (VPC) and does not see the API gateway hosting the /credentials end-point.

### Acceptance Criteria

**Given** an EC2 instance hosted on PDS AWS account on MCP have the appropriate IAM instance role to access OpenSearch
**When I perform** I  harvest or registry-mgr without authentication
**Then I expect** I expect to update the OpenSearch service configured, which is on the same AWS account.

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Here is the problem. The Java SDK v2 requires the IAM credentials. We do that via the lambda function normally. When they expire, have to go back to the lambda function with fresh token from cognito either through logging in yet again or using refresh token. So, when the credential tokens expire from the EC2, how can the Java get new credentials from the EC2 that is running the Java? The initial set can be given via system properties but those are read/set once. How can the Java say this credential is not working any more EC2, please refresh it?

The simplest way to handle this is to make the EC2 a user in the sense that it has secrets (auth) provided to java such that it can manage the credentials as it already does.

**Comment by al-niessner** [comment]
Here is sample of EC2 XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<registry_connection index="dev-registry">
<ec2_credential_url endpoint="https://p5qmxrldysl1gy759hqf.us-west-2.aoss.amazonaws.com"
>[http://localhost/AWS_CONTAINER_CREDENTIALS_RELATIVE_URI</ec2_credential_url>](http://localhost/AWS_CONTAINER_CREDENTIALS_RELATIVE_URI%3C/ec2_credential_url%3E)
</registry_connection>
````

**Comment by c-suh** [comment]
@tloubrieu-jpl and @al-niessner please provide the requisite information for me to test the completeness of this task.

**Comment by c-suh** [comment]
Already used successfully by Nucleus, so I&T is not needed.
